version: '3.9'

services:
  ubuntu:
    build:
      context: '.'
      dockerfile: './Dockerfile'
      target: 'ubuntu'
    tty: true
  arch:
    build:
      context: '.'
      dockerfile: './Dockerfile'
      target: 'arch'
    tty: true
