[window]
opacity = 0.8
option_as_alt = "Both"

[font]
size = 11

[[keyboard.bindings]]
action = "None"
key = "T"
mods = "Command"

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u0001" # Ctrl-A (行頭)

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u0005" # Ctrl-E (行末)
